version: "3.9"
services:
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    tmpfs:
      - /bitnami:mode=770,uid=1001,gid=10000
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.7'
    tmpfs:
      - /bitnami:mode=770,uid=1001,gid=10000
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,OUTSIDE://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9091,OUTSIDE://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
    extra_hosts:
      - "host.docker.internal:host-gateway"
  kafka-ui:
      image: 'provectuslabs/kafka-ui:latest'
      ports:
        - '8080:8080'
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9091
        - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
      depends_on:
        - zookeeper
        - kafka
      extra_hosts:
        - "host.docker.internal:host-gateway"
