version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    tmpfs:
      - /bitnami:mode=770,uid=1001,gid=10000
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    tmpfs:
      - /bitnami:mode=770,uid=1001,gid=10000
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    extra_hosts:
      - "host.docker.internal:host-gateway"
  kafka-ui:
      image: 'provectuslabs/kafka-ui:latest'
      ports:
        - '8080:8080'
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
      depends_on:
        - zookeeper
        - kafka
      extra_hosts:
        - "host.docker.internal:host-gateway"
