name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - uses: actions/checkout@v3
      - name: Start Services
        run: docker compose --project-directory dev-infra up -d
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: DNS
        run: echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - name: Test
        uses: gradle/gradle-build-action@v1
        with:
          arguments: test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

