name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - uses: actions/checkout@v3
      - name: Start Services
        run: docker compose --project-directory hosting/dev up -d
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: DNS
        run: echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Test
        run: |
          cd src/core
          ./gradlew test --console plain
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: report
          path: '**/test-results/test/TEST-*.xml'
          reporter: java-junit
